version: 2


builds:
  - id: duocli
    main: ./cmd/duocli/duocli.go
    binary: duocli
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    goos:
      - linux
    goarch:
      - amd64

before:
  hooks:
    - go run ./cmd/duocli/duocli.go manual --output duocli.8
    - go run ./cmd/duocli/duocli.go readme --output README.md

archives:
  - id: default
    wrap_in_directory: true
    files:
      - README.md
      - LICENSE
      - duocli.8
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else if eq .Os "linux" }}Linux
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - id: duocli
    package_name: duocli
    description: "DuoCLI is a CLI interface to the Duo Admin API."
    maintainer: "Benjamin S. Allen <bsallen@alcf.anl.gov>"
    homepage: "https://github.com/bensallen/duocli"
    license: "BSD"
    formats:
      - rpm
      - deb
    release: 1
    bindir: /usr/bin
    contents:
    - src: "duocli.8"
      dst: /usr/share/man/man8/duocli.8
    - src: scripts/bash_autocomplete
      dst: /etc/bash_completion.d/duocli
    - src: duocli.json.example
      dst: /usr/share/duocli/duocli.json.example
    file_name_template: >-
      {{ .ProjectName }}-{{ .Version }}-{{ .Release }}.
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
